export default {
  GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
  GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',

  GET_SPECIFIC_USER_REQUEST: 'GET_SPECIFIC_USER_REQUEST',
  GET_SPECIFIC_USER_SUCCESS: 'GET_SPECIFIC_USER_SUCCESS',
  GET_SPECIFIC_USER_FAILURE: 'GET_SPECIFIC_USER_FAILURE',

  GET_USER_GROUP_HISTORY_REQUEST: 'GET_USER_GROUP_HISTORY_REQUEST',
  GET_USER_GROUP_HISTORY_SUCCESS: 'GET_USER_GROUP_HISTORY_SUCCESS',
  GET_USER_GROUP_HISTORY_FAILURE: 'GET_USER_GROUP_HISTORY_FAILURE',

  GET_USER_STATUS_HISTORY_REQUEST: 'GET_USER_STATUS_HISTORY_REQUEST',
  GET_USER_STATUS_HISTORY_SUCCESS: 'GET_USER_STATUS_HISTORY_SUCCESS',
  GET_USER_STATUS_HISTORY_FAILURE: 'GET_USER_STATUS_HISTORY_FAILURE',

  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
}
